#ifndef __HANS_CHIP_8_H
#define __HANS_CHIP_8_H

#define TOTAL_MEMEORY_SIZE 4096
#define INTERPRETER_MEMORY_HOLD_START 0
#define INTERPRETER_MEMORY_HOLD_END 511
#define RESERVED_MEMORY_FOR_DISPLAY_REFRESH_START 3840
#define RESERVED_MEMORY_FOR_DISPLAY_REFRESH_END 4095
#define RESERVED_MEMORY_FOR_SYSTEM_START 3744
#define RESERVED_MEMORY_FOR_SYSTEM_END 3839

#define REG_SIZE 8
#define REG_NUMS 16
#define ADDR_REG_SIZE 12

#define STACK_SIZE 24

#define DISPLAY_RESOLUTION_ROWS 64
#define DISPLAY_RESOLUTION_COLS 32
#define DISPLAY_RESOLUTION_TOT_SIZE \
  (DISPLAY_RESOLUTION_COLS * DISPLAY_RESOLUTION_ROWS)
#define DISPLAY_LOCATION(row, col) \
  (row) * (DISPLAY_RESOLUTION_ROWS) + (DISPLAY_RESOLUTION_COLS)

#define OPCODES_TOT_NUMS 35

typedef unsigned char byte;

#endif
